[project]
name = "pytomata-marker"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "automata-lib>=9.0.0",
    "ruff>=0.9.3",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]
